import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'

export default function About() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.showcase__container}>
        <img className={styles.showcase__bgImg}/>

        <div className={styles.showcase__navbar}>
          <img className={styles.showcase__navbar__logo} />
          <button className={styles.showcase__btn__black}>About</button>
        </div>

        <div>
        </div>
      </div>
    </div>
  )
}
