import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import components
import Showcase from '../components/sections/homepage/HomeShowcase'
import CertifiedTutors from '../components/sections/homepage/CertifiedTutorsSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*--- SHOWCASE-SECTION ---*/}
      <Showcase />
      {/*-- CERTIFIED-TUTORS-SECTION --*/}
      <CertifiedTutors />
    </div>
  )
}
